config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'quotes#index'
  resources :quotes
  get 'about', to: 'quotes#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :saying, presence: true, length: { maximum: 200, minimum: 3 }
  validates :author, presence: true, length: { maximum: 80, minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quote = Quote.order("RANDOM()").first
  end

  def create
    @quote = Quote.create(quote_params)
    if @quote.invalid?
      flash[:error] = '<strong>Could not save.</strong> The data you entered is invalid.<br />
      Your note must be between 3 and 200 characters,<br />
      and your name must be between 3 and 80 characters.'
    end
    redirect_to root_path
  end

  def about
  end

  private

  def quote_params
    params.require(:quote).permit(:saying, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Love Notes</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header class="row">
      <div class="col-2">
        <div class="circle">
          <%= link_to root_path, class: 'logo' do %>
            <br />
            LOVE
            <br />
            NOTES
            <br />
          <% end %>
        </div>
      </div>
      <div class="col-5 hidden-xs-down slogan">
        Messages for your tender heart
      </div>
      <div class="col-9 col-sm-4 offset-1 links">
        <span class="float-right">
        <!-- Button trigger modal -->
        <%= link_to 'Contribute', '#', data: {toggle: 'modal', target: '#myModal'} %>
        &nbsp;
        &nbsp;
        <%= link_to 'About', about_path %>
        &nbsp;
        &nbsp;
        </span>
      </div>
    </header>



    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Share your Love Note</h4>
          </div>
          <%= simple_form_for Quote.new do |f| %>
            <div class="modal-body">
              <%= f.input :saying, label: "What do you want your love note to say?", placeholder: "Example: You are loved." %>
              <br />
              <%= f.input :author, label: "How do you want to sign this note?", placeholder: "(Your name)" %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit 'Create', class: 'btn btn-danger' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <hr />

    <br class="clear" />

    <div class="container">
      <% if flash[:error].present? %>
        <div class="col-10 offset-1 alert alert-danger">
          <%= flash[:error].html_safe %>
        </div>
      <% end %>
      <%= yield %>
    </div>

    <div class="footer">
      <div class="container">
        <div class="row">
          <div class="col-6">
            <%= link_to "Show me another love note!", root_path, class: 'next-quote' %>
          </div>
          <div class="col-6 footer-blurb">
            Proudly built with RF and love by <a href="http://www.melsencarlsburg.com/firehose/portfolio">Melsen Carlsburg</a><br />
            Want to build your own web app? <a href="http://thefirehoseproject.com">Learn how to code here!</a>
          </div>
        </div>
      </div>
    </div>


  </body>
</html>

app/views/quotes/about.html.erb
<div class="col-10 offset-1 about">
  <h1>About Love Notes</h1>
  <p>
  We can get overwhelmed by the daily stresses of life, world events, and a seemingly endless barrage of social media stories.
  </p>
  <p>
  No matter what you feel down about, sometimes it can feel nice to contrast all that chaotic information with sweet messages of love and support. I hope these messages bring a little extra happiness to your day!
  </p>
  <p>
  This list of quotes will be moderated. I ask that you please respect the intent of the project and only submit notes that are uplifting and complementary.
  </p>
  <br />

  <div class="row">
    <div class="col-12 col-sm-4">
      <%= image_tag 'hearts-bouquet.jpg', class: 'img-fluid' %>
    </div>

    <div class="col-12 col-sm-7 offset-sm-1">
      <h2 class="text-center">A note from Melsen Carlsburg</h2>
      <br />
      <p>
        This Love Notes website is my first ever web app. I just started the <a href="http://thefirehoseproject.com">Firehose Project</a>, and I'm excited to be digging into web development so much in my first week. Please help me make this app a friendly, fun place to visit by <%= link_to 'contributing', new_quote_path %> your love note!
      </p>
    </div>
  </div>

</div>

<br class="clear" />
<br />
<br />
<br />

app/views/quotes/index.html.erb
<h3 class="tagline">
  Here's a little something for you to ponder if you're feeling down:
</h3>
<br />
<h2>
<span>Love Note No. <%= @quote.id %></span>
</h2>

<h1><%= @quote.saying %></h1>
<h2 class="float-right">- <%= @quote.author %></h2>

<br class="clear" />
<br />
<br />
<br />